[package]
name = "smallrand"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

[features]
default = ["std"]
std = []

[dependencies]
[target.'cfg(not(unix))'.dependencies]
getrandom = "0.3.2"
