[package]
name = "urng"
version = "0.1.0"
edition = "2021"

[msrv]
rust-version = "1.59"

[features]
default = ["getrandom", "std"]
std = []
getrandom = []

[dependencies]
getrandom = "0.3.2"
rand = "0.9.0"
