name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            toolchain: stable
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: 1.75.0

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy with pedantic
        run: cargo clippy --all -- -W clippy::pedantic -D warnings
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build with no-default-features
        run: cargo build --verbose --no-default-features
      - name: Run tests with no-default-features
        run: cargo test --verbose --no-default-features
      - name: Build with use-getrandom
        run: cargo build --verbose --features use-getrandom
      - name: Run tests with use-getrandom
        run: cargo test --verbose --features use-getrandom
